[package]
name = "cxsh"
version = "0.1.0"
authors = ["Kaoru Chisen <cordx56@cordx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.23.0"
nom = "7.0.0"
regex = "1.5.4"
termion = "1.5.6"
